language: node_js
node_js:
  - 0.8
before_script:
  - npm install -g grunt-cli
notifications:
  email: false
  hipchat:
    - secure: "XnnH5GKWngRizFX1W4fDPFLwjkQl2HKyyDe4NNRZf6Jj76LjsulsE1osdpgw\nd1m+KK+ka0MNRimrxW8seOGNRvXKCfvldLtw/3+ZNSy0kGoOcG+M0Fg8hIsl\nT+FAHGL2D0a71Mo3k6Bj8zOFmpNREMEGUJyerEhclVh6TS27QSk="
